name: Import Blocklist
description: "A GitHub Action to import the blocklist of an organization"
branding:
  icon: "git-pull-request"
  color: red
inputs:
  sourceOrganization:
    description: "The organization you want to use as your source to import a blocklist from."
    required: true
  targetOrganization:
    description: "The organization you want to import the blocklist into."
  token:
    description: "GitHub Access Token required to get organization data."
    required: true
runs:
  using: "node12"
  main: "index.js"